spring:
    application:
        name: api-gateway

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

server:
    port: 8877

zuul:
  routes:
    account:
      path: /fetch/**
      strip-prefix: false
      url: http://localhost:8080/
    clientA:
      path: /clientA/**
      strip-prefix: false
      service-id: client-service-A

client-service-A:
  ribbon:
    ReadTimeout: 10000 
    ConnectTimeout: 5000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: false
